### ISSUE TITLE
range a-z, what about numbers?

### ISSUE THREAD

**Issue by inxomnyaa** [legoboy0215/SimpleTransfer#1]
You check for the range a-z. But as long as i know, you can use numbers as name also. And other languages like russia?

**Comment by legoboy0215** [comment]
Oh crap I forgot that. Pull Request? I have no access to my PC now :)

**Comment by inxomnyaa** [comment]
I have no idea. also, it would be better to loop through the names of every folder than to loop through letters.

**Comment by legoboy0215** [comment]
Oh yea... I am so stupid. How would I do that?

**Comment by inxomnyaa** [comment]
No idea, haven't done this for ages.
I'll search something up.

**Comment by inxomnyaa** [comment]
http://code.tutsplus.com/tutorials/quick-tip-loop-through-folders-with-phps-glob--net-11274

Look under "The second argument":
GLOB_ONLYDIR: Return only directory entries which match the pattern
Then for each folder you got loop through the files and done

**Comment by legoboy0215** [comment]
Thanks dude!!!! I will check that out :)

**Comment by inxomnyaa** [comment]
You wont even have to loop through the folder. foreach folder you found you can use glob() again, this time use "*.yml" as search pattern
EDIT:
You don't even need loops for the a-z (and others.)
Just use players/*/*.yml

**Comment by legoboy0215** [comment]
Example?

**Comment by inxomnyaa** [comment]
``` php
$path= $this->getDataPath()."/plugins/SimpleAuth/players/"; // if there is something like getPluginPath, you could also use that
foreach(glob($path."*/*.yml") as $playername)  //will search for .yml's in every subfolder of /players
    {   
        echo "Filename: " . $playername. ".yml<br />";  
    }
```

**Comment by legoboy0215** [comment]
Whoa!

**Comment by Muqsit** [comment]
So, can I use this now:3
